# Generated by Django 3.1.13 on 2021-10-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaks_app', '0004_auto_20211029_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
