# Generated by Django 3.1.13 on 2021-10-29 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peaks_app', '0005_whitelistcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedconnection',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
