# Generated by Django 3.1.13 on 2021-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peaks_app', '0006_rejectedconnection_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistcountry',
            options={'verbose_name_plural': 'WhitelistCountries'},
        ),
    ]
